spring:
  application:
    name: mancer
  datasource:
    password: Zhif-26021965$
    username: postgres
    url: jdbc:postgresql://db.ilrqqtquoofvzazyrqab.supabase.co:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://ilrqqtquoofvzazyrqab.supabase.co/auth/v1



variables:
  cors:
    url: http://localhost:5173


gcp:
  bucket:
    name: auto_location_bucket
  config:
    file: focused-waters-483521-q2-5f18e1de12bd.json


